//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace tikSystem.Web.Library.FlifoService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FlifoServiceSoap", Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlifoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback flight_informationOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_scheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_flightsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FlifoService() {
            this.Url = global::tikSystem.Web.Library.Properties.Settings.Default.tikSystem_Web_Library_FlifoService_FlifoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event flight_informationCompletedEventHandler flight_informationCompleted;
        
        /// <remarks/>
        public event get_scheduleCompletedEventHandler get_scheduleCompleted;
        
        /// <remarks/>
        public event get_flightsCompletedEventHandler get_flightsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flywithstyle.com/flifoservice/flight_information", RequestNamespace="http://www.flywithstyle.com/flifoservice", ResponseNamespace="http://www.flywithstyle.com/flifoservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FlifoResponse flight_information(FlifoRequest fReq, string base64SHA1, UserCredentials userCredeitial) {
            object[] results = this.Invoke("flight_information", new object[] {
                        fReq,
                        base64SHA1,
                        userCredeitial});
            return ((FlifoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void flight_informationAsync(FlifoRequest fReq, string base64SHA1, UserCredentials userCredeitial) {
            this.flight_informationAsync(fReq, base64SHA1, userCredeitial, null);
        }
        
        /// <remarks/>
        public void flight_informationAsync(FlifoRequest fReq, string base64SHA1, UserCredentials userCredeitial, object userState) {
            if ((this.flight_informationOperationCompleted == null)) {
                this.flight_informationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onflight_informationOperationCompleted);
            }
            this.InvokeAsync("flight_information", new object[] {
                        fReq,
                        base64SHA1,
                        userCredeitial}, this.flight_informationOperationCompleted, userState);
        }
        
        private void Onflight_informationOperationCompleted(object arg) {
            if ((this.flight_informationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.flight_informationCompleted(this, new flight_informationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flywithstyle.com/flifoservice/get_schedule", RequestNamespace="http://www.flywithstyle.com/flifoservice", ResponseNamespace="http://www.flywithstyle.com/flifoservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScheduleResponse get_schedule(ScheduleRequest creq, string base64SHA1, UserCredentials userCredeitial) {
            object[] results = this.Invoke("get_schedule", new object[] {
                        creq,
                        base64SHA1,
                        userCredeitial});
            return ((ScheduleResponse)(results[0]));
        }
        
        /// <remarks/>
        public void get_scheduleAsync(ScheduleRequest creq, string base64SHA1, UserCredentials userCredeitial) {
            this.get_scheduleAsync(creq, base64SHA1, userCredeitial, null);
        }
        
        /// <remarks/>
        public void get_scheduleAsync(ScheduleRequest creq, string base64SHA1, UserCredentials userCredeitial, object userState) {
            if ((this.get_scheduleOperationCompleted == null)) {
                this.get_scheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_scheduleOperationCompleted);
            }
            this.InvokeAsync("get_schedule", new object[] {
                        creq,
                        base64SHA1,
                        userCredeitial}, this.get_scheduleOperationCompleted, userState);
        }
        
        private void Onget_scheduleOperationCompleted(object arg) {
            if ((this.get_scheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_scheduleCompleted(this, new get_scheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flywithstyle.com/flifoservice/get_flights", RequestNamespace="http://www.flywithstyle.com/flifoservice", ResponseNamespace="http://www.flywithstyle.com/flifoservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FlightsResponse get_flights(FlightsRequest freq, string base64SHA1, UserCredentials userCredeitial) {
            object[] results = this.Invoke("get_flights", new object[] {
                        freq,
                        base64SHA1,
                        userCredeitial});
            return ((FlightsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void get_flightsAsync(FlightsRequest freq, string base64SHA1, UserCredentials userCredeitial) {
            this.get_flightsAsync(freq, base64SHA1, userCredeitial, null);
        }
        
        /// <remarks/>
        public void get_flightsAsync(FlightsRequest freq, string base64SHA1, UserCredentials userCredeitial, object userState) {
            if ((this.get_flightsOperationCompleted == null)) {
                this.get_flightsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_flightsOperationCompleted);
            }
            this.InvokeAsync("get_flights", new object[] {
                        freq,
                        base64SHA1,
                        userCredeitial}, this.get_flightsOperationCompleted, userState);
        }
        
        private void Onget_flightsOperationCompleted(object arg) {
            if ((this.get_flightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_flightsCompleted(this, new get_flightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlifoRequest {
        
        private string airline_rcdField;
        
        private int flight_numberField;
        
        private System.DateTime flight_date_fromField;
        
        private System.DateTime flight_date_toField;
        
        private string flight_information_1_updateField;
        
        private string flight_information_1Field;
        
        private string flight_information_2_updateField;
        
        private string flight_information_2Field;
        
        private string flight_information_3_updateField;
        
        private string flight_information_3Field;
        
        /// <remarks/>
        public string airline_rcd {
            get {
                return this.airline_rcdField;
            }
            set {
                this.airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public int flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flight_date_from {
            get {
                return this.flight_date_fromField;
            }
            set {
                this.flight_date_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flight_date_to {
            get {
                return this.flight_date_toField;
            }
            set {
                this.flight_date_toField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_1_update {
            get {
                return this.flight_information_1_updateField;
            }
            set {
                this.flight_information_1_updateField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_1 {
            get {
                return this.flight_information_1Field;
            }
            set {
                this.flight_information_1Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_2_update {
            get {
                return this.flight_information_2_updateField;
            }
            set {
                this.flight_information_2_updateField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_2 {
            get {
                return this.flight_information_2Field;
            }
            set {
                this.flight_information_2Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_3_update {
            get {
                return this.flight_information_3_updateField;
            }
            set {
                this.flight_information_3_updateField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_3 {
            get {
                return this.flight_information_3Field;
            }
            set {
                this.flight_information_3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlightLegs {
        
        private string flight_idField;
        
        private string departure_airport_rcdField;
        
        private System.Nullable<System.DateTime> departure_dateField;
        
        private System.Nullable<System.DateTime> utc_departure_date_timeField;
        
        private string planned_departure_timeField;
        
        private string arrival_airport_rcdField;
        
        private System.Nullable<System.DateTime> arrival_dateField;
        
        private System.Nullable<System.DateTime> utc_arrival_date_timeField;
        
        private string planned_arrival_timeField;
        
        /// <remarks/>
        public string flight_id {
            get {
                return this.flight_idField;
            }
            set {
                this.flight_idField = value;
            }
        }
        
        /// <remarks/>
        public string departure_airport_rcd {
            get {
                return this.departure_airport_rcdField;
            }
            set {
                this.departure_airport_rcdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> departure_date {
            get {
                return this.departure_dateField;
            }
            set {
                this.departure_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> utc_departure_date_time {
            get {
                return this.utc_departure_date_timeField;
            }
            set {
                this.utc_departure_date_timeField = value;
            }
        }
        
        /// <remarks/>
        public string planned_departure_time {
            get {
                return this.planned_departure_timeField;
            }
            set {
                this.planned_departure_timeField = value;
            }
        }
        
        /// <remarks/>
        public string arrival_airport_rcd {
            get {
                return this.arrival_airport_rcdField;
            }
            set {
                this.arrival_airport_rcdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> arrival_date {
            get {
                return this.arrival_dateField;
            }
            set {
                this.arrival_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> utc_arrival_date_time {
            get {
                return this.utc_arrival_date_timeField;
            }
            set {
                this.utc_arrival_date_timeField = value;
            }
        }
        
        /// <remarks/>
        public string planned_arrival_time {
            get {
                return this.planned_arrival_timeField;
            }
            set {
                this.planned_arrival_timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class Flights {
        
        private string flight_idField;
        
        private System.Nullable<System.DateTime> utc_departure_dateField;
        
        private string airline_rcdField;
        
        private string flight_numberField;
        
        private string flight_status_rcdField;
        
        private string aircraft_type_rcdField;
        
        private string matriculation_rcdField;
        
        private string operating_airline_rcdField;
        
        private string operating_flight_numberField;
        
        private string origin_rcdField;
        
        private string destination_rcdField;
        
        private string flight_commentField;
        
        private string internal_commentField;
        
        private string controlling_agency_codeField;
        
        private string schedule_idField;
        
        private System.Nullable<byte> free_seating_flagField;
        
        private System.Nullable<byte> auto_open_checkin_flagField;
        
        private System.Nullable<byte> allow_web_checkin_flagField;
        
        private string flight_information_1Field;
        
        private string flight_information_2Field;
        
        private string flight_information_3Field;
        
        private System.Nullable<byte> exclude_statistics_flagField;
        
        private string dot_reporting_date_timeField;
        
        private FlightLegs[] flight_legsField;
        
        /// <remarks/>
        public string flight_id {
            get {
                return this.flight_idField;
            }
            set {
                this.flight_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> utc_departure_date {
            get {
                return this.utc_departure_dateField;
            }
            set {
                this.utc_departure_dateField = value;
            }
        }
        
        /// <remarks/>
        public string airline_rcd {
            get {
                return this.airline_rcdField;
            }
            set {
                this.airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public string flight_status_rcd {
            get {
                return this.flight_status_rcdField;
            }
            set {
                this.flight_status_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string aircraft_type_rcd {
            get {
                return this.aircraft_type_rcdField;
            }
            set {
                this.aircraft_type_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string matriculation_rcd {
            get {
                return this.matriculation_rcdField;
            }
            set {
                this.matriculation_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string operating_airline_rcd {
            get {
                return this.operating_airline_rcdField;
            }
            set {
                this.operating_airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string operating_flight_number {
            get {
                return this.operating_flight_numberField;
            }
            set {
                this.operating_flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public string origin_rcd {
            get {
                return this.origin_rcdField;
            }
            set {
                this.origin_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string destination_rcd {
            get {
                return this.destination_rcdField;
            }
            set {
                this.destination_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_comment {
            get {
                return this.flight_commentField;
            }
            set {
                this.flight_commentField = value;
            }
        }
        
        /// <remarks/>
        public string internal_comment {
            get {
                return this.internal_commentField;
            }
            set {
                this.internal_commentField = value;
            }
        }
        
        /// <remarks/>
        public string controlling_agency_code {
            get {
                return this.controlling_agency_codeField;
            }
            set {
                this.controlling_agency_codeField = value;
            }
        }
        
        /// <remarks/>
        public string schedule_id {
            get {
                return this.schedule_idField;
            }
            set {
                this.schedule_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> free_seating_flag {
            get {
                return this.free_seating_flagField;
            }
            set {
                this.free_seating_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> auto_open_checkin_flag {
            get {
                return this.auto_open_checkin_flagField;
            }
            set {
                this.auto_open_checkin_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> allow_web_checkin_flag {
            get {
                return this.allow_web_checkin_flagField;
            }
            set {
                this.allow_web_checkin_flagField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_1 {
            get {
                return this.flight_information_1Field;
            }
            set {
                this.flight_information_1Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_2 {
            get {
                return this.flight_information_2Field;
            }
            set {
                this.flight_information_2Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_3 {
            get {
                return this.flight_information_3Field;
            }
            set {
                this.flight_information_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> exclude_statistics_flag {
            get {
                return this.exclude_statistics_flagField;
            }
            set {
                this.exclude_statistics_flagField = value;
            }
        }
        
        /// <remarks/>
        public string dot_reporting_date_time {
            get {
                return this.dot_reporting_date_timeField;
            }
            set {
                this.dot_reporting_date_timeField = value;
            }
        }
        
        /// <remarks/>
        public FlightLegs[] flight_legs {
            get {
                return this.flight_legsField;
            }
            set {
                this.flight_legsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlightsResponse {
        
        private Flights[] flightsField;
        
        private string resultField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public Flights[] Flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
            }
        }
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlightsRequest {
        
        private System.DateTime departure_date_fromField;
        
        private System.DateTime departure_date_toField;
        
        private string airline_rcdField;
        
        private string flight_numberField;
        
        private string origin_rcdField;
        
        private string destination_rcdField;
        
        /// <remarks/>
        public System.DateTime departure_date_from {
            get {
                return this.departure_date_fromField;
            }
            set {
                this.departure_date_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime departure_date_to {
            get {
                return this.departure_date_toField;
            }
            set {
                this.departure_date_toField = value;
            }
        }
        
        /// <remarks/>
        public string airline_rcd {
            get {
                return this.airline_rcdField;
            }
            set {
                this.airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public string origin_rcd {
            get {
                return this.origin_rcdField;
            }
            set {
                this.origin_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string destination_rcd {
            get {
                return this.destination_rcdField;
            }
            set {
                this.destination_rcdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class ScheduleFlightLeg {
        
        private string schedule_idField;
        
        private string departure_airport_rcdField;
        
        private string planned_departure_timeField;
        
        private string arrival_airport_rcdField;
        
        private string planned_arrival_timeField;
        
        private string boarding_timeField;
        
        private string boarding_gateField;
        
        private string arrival_gateField;
        
        private System.Nullable<int> checkin_pnl_hoursField;
        
        private System.Nullable<int> open_flight_hoursField;
        
        /// <remarks/>
        public string schedule_id {
            get {
                return this.schedule_idField;
            }
            set {
                this.schedule_idField = value;
            }
        }
        
        /// <remarks/>
        public string departure_airport_rcd {
            get {
                return this.departure_airport_rcdField;
            }
            set {
                this.departure_airport_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string planned_departure_time {
            get {
                return this.planned_departure_timeField;
            }
            set {
                this.planned_departure_timeField = value;
            }
        }
        
        /// <remarks/>
        public string arrival_airport_rcd {
            get {
                return this.arrival_airport_rcdField;
            }
            set {
                this.arrival_airport_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string planned_arrival_time {
            get {
                return this.planned_arrival_timeField;
            }
            set {
                this.planned_arrival_timeField = value;
            }
        }
        
        /// <remarks/>
        public string boarding_time {
            get {
                return this.boarding_timeField;
            }
            set {
                this.boarding_timeField = value;
            }
        }
        
        /// <remarks/>
        public string boarding_gate {
            get {
                return this.boarding_gateField;
            }
            set {
                this.boarding_gateField = value;
            }
        }
        
        /// <remarks/>
        public string arrival_gate {
            get {
                return this.arrival_gateField;
            }
            set {
                this.arrival_gateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> checkin_pnl_hours {
            get {
                return this.checkin_pnl_hoursField;
            }
            set {
                this.checkin_pnl_hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> open_flight_hours {
            get {
                return this.open_flight_hoursField;
            }
            set {
                this.open_flight_hoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class Schedule {
        
        private string schedule_idField;
        
        private System.Nullable<System.DateTime> flight_date_fromField;
        
        private System.Nullable<System.DateTime> flight_date_toField;
        
        private System.Nullable<byte> mon_flagField;
        
        private System.Nullable<byte> tue_flagField;
        
        private System.Nullable<byte> wed_flagField;
        
        private System.Nullable<byte> thu_flagField;
        
        private System.Nullable<byte> fri_flagField;
        
        private System.Nullable<byte> sat_flagField;
        
        private System.Nullable<byte> sun_flagField;
        
        private System.Nullable<byte> flight_generated_flagField;
        
        private string controlling_agency_codeField;
        
        private string operating_airline_rcdField;
        
        private string airline_rcdField;
        
        private string aircraft_type_rcdField;
        
        private string origin_rcdField;
        
        private string destination_rcdField;
        
        private string schedule_commentField;
        
        private string matriculation_rcdField;
        
        private string flight_status_rcdField;
        
        private string flight_numberField;
        
        private string operating_flight_numberField;
        
        private System.Nullable<byte> auto_open_checkin_flagField;
        
        private System.Nullable<byte> allow_web_checkin_flagField;
        
        private string flight_information_1Field;
        
        private string flight_information_2Field;
        
        private string flight_information_3Field;
        
        private System.Nullable<byte> hide_from_availability_flagField;
        
        private System.Nullable<byte> distribute_schedule_flagField;
        
        private System.Nullable<byte> e_ticket_flagField;
        
        private System.Nullable<byte> non_smoking_flagField;
        
        private System.Nullable<byte> exclude_statistics_flagField;
        
        private string schedule_group_idField;
        
        private string service_type_rcdField;
        
        private System.Nullable<byte> send_avs_message_flagField;
        
        private System.Nullable<byte> exclude_pnl_flagField;
        
        private System.Nullable<byte> exclude_pfs_flagField;
        
        private System.Nullable<System.DateTime> schedule_distribute_date_timeField;
        
        private ScheduleFlightLeg[] flightLegsField;
        
        /// <remarks/>
        public string schedule_id {
            get {
                return this.schedule_idField;
            }
            set {
                this.schedule_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> flight_date_from {
            get {
                return this.flight_date_fromField;
            }
            set {
                this.flight_date_fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> flight_date_to {
            get {
                return this.flight_date_toField;
            }
            set {
                this.flight_date_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> mon_flag {
            get {
                return this.mon_flagField;
            }
            set {
                this.mon_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> tue_flag {
            get {
                return this.tue_flagField;
            }
            set {
                this.tue_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> wed_flag {
            get {
                return this.wed_flagField;
            }
            set {
                this.wed_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> thu_flag {
            get {
                return this.thu_flagField;
            }
            set {
                this.thu_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> fri_flag {
            get {
                return this.fri_flagField;
            }
            set {
                this.fri_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> sat_flag {
            get {
                return this.sat_flagField;
            }
            set {
                this.sat_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> sun_flag {
            get {
                return this.sun_flagField;
            }
            set {
                this.sun_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> flight_generated_flag {
            get {
                return this.flight_generated_flagField;
            }
            set {
                this.flight_generated_flagField = value;
            }
        }
        
        /// <remarks/>
        public string controlling_agency_code {
            get {
                return this.controlling_agency_codeField;
            }
            set {
                this.controlling_agency_codeField = value;
            }
        }
        
        /// <remarks/>
        public string operating_airline_rcd {
            get {
                return this.operating_airline_rcdField;
            }
            set {
                this.operating_airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string airline_rcd {
            get {
                return this.airline_rcdField;
            }
            set {
                this.airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string aircraft_type_rcd {
            get {
                return this.aircraft_type_rcdField;
            }
            set {
                this.aircraft_type_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string origin_rcd {
            get {
                return this.origin_rcdField;
            }
            set {
                this.origin_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string destination_rcd {
            get {
                return this.destination_rcdField;
            }
            set {
                this.destination_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string schedule_comment {
            get {
                return this.schedule_commentField;
            }
            set {
                this.schedule_commentField = value;
            }
        }
        
        /// <remarks/>
        public string matriculation_rcd {
            get {
                return this.matriculation_rcdField;
            }
            set {
                this.matriculation_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_status_rcd {
            get {
                return this.flight_status_rcdField;
            }
            set {
                this.flight_status_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public string operating_flight_number {
            get {
                return this.operating_flight_numberField;
            }
            set {
                this.operating_flight_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> auto_open_checkin_flag {
            get {
                return this.auto_open_checkin_flagField;
            }
            set {
                this.auto_open_checkin_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> allow_web_checkin_flag {
            get {
                return this.allow_web_checkin_flagField;
            }
            set {
                this.allow_web_checkin_flagField = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_1 {
            get {
                return this.flight_information_1Field;
            }
            set {
                this.flight_information_1Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_2 {
            get {
                return this.flight_information_2Field;
            }
            set {
                this.flight_information_2Field = value;
            }
        }
        
        /// <remarks/>
        public string flight_information_3 {
            get {
                return this.flight_information_3Field;
            }
            set {
                this.flight_information_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> hide_from_availability_flag {
            get {
                return this.hide_from_availability_flagField;
            }
            set {
                this.hide_from_availability_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> distribute_schedule_flag {
            get {
                return this.distribute_schedule_flagField;
            }
            set {
                this.distribute_schedule_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> e_ticket_flag {
            get {
                return this.e_ticket_flagField;
            }
            set {
                this.e_ticket_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> non_smoking_flag {
            get {
                return this.non_smoking_flagField;
            }
            set {
                this.non_smoking_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> exclude_statistics_flag {
            get {
                return this.exclude_statistics_flagField;
            }
            set {
                this.exclude_statistics_flagField = value;
            }
        }
        
        /// <remarks/>
        public string schedule_group_id {
            get {
                return this.schedule_group_idField;
            }
            set {
                this.schedule_group_idField = value;
            }
        }
        
        /// <remarks/>
        public string service_type_rcd {
            get {
                return this.service_type_rcdField;
            }
            set {
                this.service_type_rcdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> send_avs_message_flag {
            get {
                return this.send_avs_message_flagField;
            }
            set {
                this.send_avs_message_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> exclude_pnl_flag {
            get {
                return this.exclude_pnl_flagField;
            }
            set {
                this.exclude_pnl_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> exclude_pfs_flag {
            get {
                return this.exclude_pfs_flagField;
            }
            set {
                this.exclude_pfs_flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> schedule_distribute_date_time {
            get {
                return this.schedule_distribute_date_timeField;
            }
            set {
                this.schedule_distribute_date_timeField = value;
            }
        }
        
        /// <remarks/>
        public ScheduleFlightLeg[] flightLegs {
            get {
                return this.flightLegsField;
            }
            set {
                this.flightLegsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class ScheduleResponse {
        
        private Schedule[] schedulesField;
        
        private string resultField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public Schedule[] schedules {
            get {
                return this.schedulesField;
            }
            set {
                this.schedulesField = value;
            }
        }
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class ScheduleRequest {
        
        private System.DateTime departure_date_fromField;
        
        private System.DateTime departure_date_toField;
        
        private string airline_rcdField;
        
        private string flight_numberField;
        
        private string origin_rcdField;
        
        private string destination_rcdField;
        
        /// <remarks/>
        public System.DateTime departure_date_from {
            get {
                return this.departure_date_fromField;
            }
            set {
                this.departure_date_fromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime departure_date_to {
            get {
                return this.departure_date_toField;
            }
            set {
                this.departure_date_toField = value;
            }
        }
        
        /// <remarks/>
        public string airline_rcd {
            get {
                return this.airline_rcdField;
            }
            set {
                this.airline_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string flight_number {
            get {
                return this.flight_numberField;
            }
            set {
                this.flight_numberField = value;
            }
        }
        
        /// <remarks/>
        public string origin_rcd {
            get {
                return this.origin_rcdField;
            }
            set {
                this.origin_rcdField = value;
            }
        }
        
        /// <remarks/>
        public string destination_rcd {
            get {
                return this.destination_rcdField;
            }
            set {
                this.destination_rcdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class FlifoResponse {
        
        private string resultField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flywithstyle.com/flifoservice")]
    public partial class UserCredentials {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void flight_informationCompletedEventHandler(object sender, flight_informationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class flight_informationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal flight_informationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlifoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlifoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void get_scheduleCompletedEventHandler(object sender, get_scheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_scheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_scheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScheduleResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScheduleResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void get_flightsCompletedEventHandler(object sender, get_flightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_flightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_flightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlightsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlightsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591