//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tikSystem.Web.Library.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.flywithstyle.com/TPC/WEMS/Language.asmx")]
        public string tikSystem_Web_Library_MultiLanguage_ServiceEngine {
            get {
                return ((string)(this["tikSystem_Web_Library_MultiLanguage_ServiceEngine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tsuat.aceinsurance.com.au/CRS_ACORD_WS/ACORDService.asmx")]
        public string tikSystem_Web_Library_AceInsurance_ACORDService {
            get {
                return ((string)(this["tikSystem_Web_Library_AceInsurance_ACORDService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://rem.kessai.info/KessaiTest/Yoyaku.asmx")]
        public string tikSystem_Web_Library_RemWSDL_Yoyaku {
            get {
                return ((string)(this["tikSystem_Web_Library_RemWSDL_Yoyaku"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.flywithstyle.com/flifoservice_new/FlifoService.asmx")]
        public string tikSystem_Web_Library_FlifoService_FlifoService {
            get {
                return ((string)(this["tikSystem_Web_Library_FlifoService_FlifoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:12166/tikAeroWebService.asmx")]
        public string tikSystem_Web_Library_tikAeroWebService_tikAeroService {
            get {
                return ((string)(this["tikSystem_Web_Library_tikAeroWebService_tikAeroService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev-web-3402/WebService/AgentService.asmx")]
        public string tikSystem_Web_Library_agentservice_TikAero_x0020_XML_x0020_web_x0020_service {
            get {
                return ((string)(this["tikSystem_Web_Library_agentservice_TikAero_x0020_XML_x0020_web_x0020_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SSRInventoryService/SSRInventoryService.asmx")]
        public string tikSystem_Web_Library_SSRInventoryService_SSRInventoryService {
            get {
                return ((string)(this["tikSystem_Web_Library_SSRInventoryService_SSRInventoryService"]));
            }
        }
    }
}
