//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace tikSystem.Web.Library.SSRInventoryService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SSRInventoryServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SSRInventoryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSSRInventoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SSRInventoryService() {
            this.Url = global::tikSystem.Web.Library.Properties.Settings.Default.tikSystem_Web_Library_SSRInventoryService_SSRInventoryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSSRInventoryCompletedEventHandler GetSSRInventoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSSRInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SSRInventoryResponse GetSSRInventory(SSRInventoryRequest ssrInventoryRequest, UserCredential userCredential) {
            object[] results = this.Invoke("GetSSRInventory", new object[] {
                        ssrInventoryRequest,
                        userCredential});
            return ((SSRInventoryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetSSRInventoryAsync(SSRInventoryRequest ssrInventoryRequest, UserCredential userCredential) {
            this.GetSSRInventoryAsync(ssrInventoryRequest, userCredential, null);
        }
        
        /// <remarks/>
        public void GetSSRInventoryAsync(SSRInventoryRequest ssrInventoryRequest, UserCredential userCredential, object userState) {
            if ((this.GetSSRInventoryOperationCompleted == null)) {
                this.GetSSRInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSSRInventoryOperationCompleted);
            }
            this.InvokeAsync("GetSSRInventory", new object[] {
                        ssrInventoryRequest,
                        userCredential}, this.GetSSRInventoryOperationCompleted, userState);
        }
        
        private void OnGetSSRInventoryOperationCompleted(object arg) {
            if ((this.GetSSRInventoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSSRInventoryCompleted(this, new GetSSRInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SSRInventoryRequest {
        
        private string flightIdField;
        
        /// <remarks/>
        public string FlightId {
            get {
                return this.flightIdField;
            }
            set {
                this.flightIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SSRInventory {
        
        private string special_Service_Inventory_FlightIdField;
        
        private string boarding_Class_RcdField;
        
        private string special_Service_Group_Inventory_RcdField;
        
        private string special_Service_RcdField;
        
        private int bookable_CapacityField;
        
        private int request_CapacityField;
        
        private int group_Booked_CountField;
        
        private int booked_CountField;
        
        private int group_Requested_CountField;
        
        private int requested_CountField;
        
        private string status_CodeField;
        
        /// <remarks/>
        public string Special_Service_Inventory_FlightId {
            get {
                return this.special_Service_Inventory_FlightIdField;
            }
            set {
                this.special_Service_Inventory_FlightIdField = value;
            }
        }
        
        /// <remarks/>
        public string Boarding_Class_Rcd {
            get {
                return this.boarding_Class_RcdField;
            }
            set {
                this.boarding_Class_RcdField = value;
            }
        }
        
        /// <remarks/>
        public string Special_Service_Group_Inventory_Rcd {
            get {
                return this.special_Service_Group_Inventory_RcdField;
            }
            set {
                this.special_Service_Group_Inventory_RcdField = value;
            }
        }
        
        /// <remarks/>
        public string Special_Service_Rcd {
            get {
                return this.special_Service_RcdField;
            }
            set {
                this.special_Service_RcdField = value;
            }
        }
        
        /// <remarks/>
        public int Bookable_Capacity {
            get {
                return this.bookable_CapacityField;
            }
            set {
                this.bookable_CapacityField = value;
            }
        }
        
        /// <remarks/>
        public int Request_Capacity {
            get {
                return this.request_CapacityField;
            }
            set {
                this.request_CapacityField = value;
            }
        }
        
        /// <remarks/>
        public int Group_Booked_Count {
            get {
                return this.group_Booked_CountField;
            }
            set {
                this.group_Booked_CountField = value;
            }
        }
        
        /// <remarks/>
        public int Booked_Count {
            get {
                return this.booked_CountField;
            }
            set {
                this.booked_CountField = value;
            }
        }
        
        /// <remarks/>
        public int Group_Requested_Count {
            get {
                return this.group_Requested_CountField;
            }
            set {
                this.group_Requested_CountField = value;
            }
        }
        
        /// <remarks/>
        public int Requested_Count {
            get {
                return this.requested_CountField;
            }
            set {
                this.requested_CountField = value;
            }
        }
        
        /// <remarks/>
        public string Status_Code {
            get {
                return this.status_CodeField;
            }
            set {
                this.status_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SSRInventoryResponse {
        
        private SSRInventory[] sSRInventoriesField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public SSRInventory[] SSRInventories {
            get {
                return this.sSRInventoriesField;
            }
            set {
                this.sSRInventoriesField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserCredential {
        
        private string agencyCodeField;
        
        private string passwordField;
        
        /// <remarks/>
        public string AgencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetSSRInventoryCompletedEventHandler(object sender, GetSSRInventoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSSRInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSSRInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSRInventoryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSRInventoryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591